packages:
  - .

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild

blockExoticSubdeps: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@usehercules/*"
allowBuilds:
  '@clerk/shared': false
  '@swc/core': true
  core-js: true
  esbuild: true
